# Add local bin directory to path
export PATH="$HOME/.local/bin:$PATH"

# Path to the dotfiles root directory
export DOTFILES="__DOTFILES_PATH__"

# Set the default editor in Terminal
export EDITOR='nano'

# --- Source aliases ---
source "$DOTFILES/zsh/aliases.zsh"

# --- Ensure Starship is active/enabled ---
eval "$(starship init zsh)"

# --- Add zsh-autosuggestions ---
source "$DOTFILES/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
bindkey '\e[C' autosuggest-accept   # accept with right arrow
